### ISSUE TITLE
PERSON: Notizen bearbeiten

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_dsj#15]
### Aktuelles Verhalten:
Beim Versuch eine Notiz auf einer Person zu bearbeiten wird man auf eine 500er Fehlerseite weitergeleitet.
 
### Gewünschtes Verhalten:
Die Notizen auf einer Person sollen bearbeitet werden können.
 
### Schritte zu reproduzieren:
 - Nach dem Login auf das Personen-Tab einer beliebigen Gruppe.
 - Eine Person auswählen.
 - Auf das Bearbeiten-Symbol klicken.
 
### Hitobito Version:
1.27.21

### Organisation
DSJ

### Screenshot:
![image](https://user-images.githubusercontent.com/69250571/171010420-e78d542c-025d-44b2-b972-9c7cf719b7b7.png)
 
### Sentry-Issue:
https://sentry.puzzle.ch/pitc/hitobito-backend/issues/47602/?query=is%3Aunresolved%20project%3Adsj

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/hitobito/blob/master/app/controllers/people_controller.rb#L40

Beim people_controller laden wir noch erst die gruppe und person, damit sie sicher beim UI rendern vorhanden ist.
